# Generated by Django 4.0 on 2022-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='stats',
            field=models.IntegerField(default=0),
        ),
    ]
