# Generated by Django 4.0 on 2022-01-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subcourse_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='subtitile',
            new_name='subtitle',
        ),
    ]
