# Generated by Django 4.0 on 2022-01-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_subtitile_subcourse_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='subtitle',
            new_name='subtitile',
        ),
    ]
