# Generated by Django 4.0 on 2022-01-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subtitle_subcourse_subtitile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='subtitile',
            new_name='subtitle',
        ),
    ]
